### ISSUE TITLE
Code fence labels work in  VS Code Preview but not Sphinx

### ISSUE THREAD

**Issue by psychemedia** [agoose77/markdown-it-mermaid#1]
I note you are using code fence labels of the form ` ```mermaid ` rather than the MyST/ `sphinxcontrib.mermaid` parsed convention ```{mermaid}` (which derives from the rst `.. mermaid::` form).

This forces folk into a position of having to use a different convention in a previewing editor to the form may be required when rendering the same document into a  static "published" form.

**Comment by agoose77** [comment]
Hmm, I wasn't aware that this was supported in Sphinx (or at least, I am not currently aware!)

This addon also doesn't support the MyST `:::` fences either. Perhaps we need to look at releasing a separate addon (or multiple MarkdownIt plugins). I'll think about this, thanks!

**Comment by psychemedia** [comment]
I render mermaid in sphinx using https://github.com/mgaitan/sphinxcontrib-mermaid which I assume is then handled in the ` ```{mermaid}` style formulation via Jupyter Book's MyST handlers?
