### ISSUE TITLE
Add Readthedocs

### ISSUE THREAD

**Issue by bollwyvl** [agoose77/markdown-it-mermaid#5]
I've started the process for https://readthedocs.org/projects/markdown-it-mermaid/

It looks like it needs an _Owner_ to finish the setup:

https://readthedocs.org/dashboard/markdown-it-mermaid/integrations/

**Comment by agoose77** [comment]
Thanks! Can you add me on RTD? (agoose77)

**Comment by bollwyvl** [comment]
Should be an open invite.

**Comment by bollwyvl** [comment]
![Screenshot from 2022-09-17 17-26-42](https://user-images.githubusercontent.com/45380/190878300-9910174f-0a3e-4bc7-8bd0-a3e47074d4a1.png)

**Comment by agoose77** [comment]
I can see the webhook on the GH repo and RTD, so I think I can close this.

**Comment by bollwyvl** [comment]
Yep. PR builds are working over on #6
